import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[font]
size = 10.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[window]
opacity = 0.9

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

